from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Tuple

import pyarrow as pa
from dateutil import parser


@dataclass
class TableSpec:
    name: str
    primary_keys: Tuple[str, ...]
    type_hints: Dict[str, pa.DataType]


COMMON_TYPE_HINTS: Dict[str, pa.DataType] = {
    "id": pa.int64(),
    "gameId": pa.int64(),
    "playerId": pa.int64(),
    "teamId": pa.int64(),
    "homeTeamId": pa.int64(),
    "awayTeamId": pa.int64(),
    "season": pa.int32(),
    "year": pa.int32(),
    "week": pa.int32(),
    "date": pa.string(),
    "startTime": pa.timestamp("s"),
    "endTime": pa.timestamp("s"),
}

TABLE_SPECS: Dict[str, TableSpec] = {
    "dim_teams": TableSpec("dim_teams", ("teamId",), {"teamId": pa.int64(), "school": pa.string()}),
    "dim_conferences": TableSpec("dim_conferences", ("id",), {"id": pa.int64(), "name": pa.string()}),
    "dim_venues": TableSpec("dim_venues", ("id",), {"id": pa.int64(), "name": pa.string()}),
    "dim_lines_providers": TableSpec("dim_lines_providers", ("id",), {"id": pa.int64(), "name": pa.string()}),
    "dim_play_types": TableSpec("dim_play_types", ("id",), {"id": pa.int64(), "text": pa.string()}),
    "fct_games": TableSpec(
        "fct_games",
        ("gameId",),
        {
            "gameId": pa.int64(),
            "homeSeed": pa.string(),
            "awaySeed": pa.string(),
        },
    ),
    "fct_game_media": TableSpec("fct_game_media", ("gameId",), {"gameId": pa.int64()}),
    "fct_lines": TableSpec(
        "fct_lines",
        ("gameId", "provider"),
        {"gameId": pa.int64(), "provider": pa.string()},
    ),
    "fct_game_teams": TableSpec(
        "fct_game_teams",
        ("gameId", "teamId"),
        {
            "gameId": pa.int64(),
            "teamId": pa.int64(),
            "pace": pa.float64(),
            "teamSeed": pa.string(),
            "opponentSeed": pa.string(),
        },
    ),
    "fct_game_players": TableSpec("fct_game_players", ("gameId", "playerId"), {"gameId": pa.int64(), "playerId": pa.int64()}),
    "fct_pbp_game_team_stats": TableSpec(
        "fct_pbp_game_team_stats",
        ("gameId", "teamId"),
        {
            "gameId": pa.int64(),
            "teamId": pa.int64(),
            "opponentId": pa.int64(),
            "season": pa.int32(),
            "date": pa.string(),
            "points": pa.int64(),
            "opp_points": pa.int64(),
            "possessions": pa.float64(),
            "possessions_ends": pa.int64(),
            "possessions_formula": pa.float64(),
            "fga": pa.int64(),
            "fg2a": pa.int64(),
            "fg2m": pa.int64(),
            "fg3a": pa.int64(),
            "fg3m": pa.int64(),
            "fta": pa.int64(),
            "ftm": pa.int64(),
            "oreb": pa.int64(),
            "turnovers": pa.int64(),
            "ppp": pa.float64(),
            "pace": pa.float64(),
            "off_eff": pa.float64(),
            "def_eff": pa.float64(),
            "adj_off_eff": pa.float64(),
            "adj_def_eff": pa.float64(),
            "pts_2": pa.int64(),
            "pts_3": pa.int64(),
            "pts_ft": pa.int64(),
            "game_minutes": pa.float64(),
            "max_period": pa.int64(),
        },
    ),
    "fct_pbp_plays_enriched": TableSpec(
        "fct_pbp_plays_enriched",
        ("id",),
        {
            "id": pa.int64(),
            "gameId": pa.int64(),
            "teamId": pa.int64(),
            "opponentId": pa.int64(),
            "period": pa.int64(),
            "secondsRemaining": pa.int64(),
            "playType": pa.string(),
            "playText": pa.string(),
            "scoringPlay": pa.bool_(),
            "shootingPlay": pa.bool_(),
            "scoreValue": pa.float64(),
            "gameStartDate": pa.string(),
            "homeScore": pa.int64(),
            "awayScore": pa.int64(),
            "isHomeTeam": pa.bool_(),
            "possession_id": pa.int64(),
            "offense_team_id": pa.int64(),
            "defense_team_id": pa.int64(),
            "possession_end": pa.bool_(),
            "garbage_time": pa.bool_(),
            "shot_shooter_id": pa.int64(),
            "shot_shooter_name": pa.string(),
            "shot_made": pa.bool_(),
            "shot_range": pa.string(),
            "shot_assisted": pa.bool_(),
            "shot_assisted_by_id": pa.int64(),
            "shot_assisted_by_name": pa.string(),
            "shot_loc_x": pa.float64(),
            "shot_loc_y": pa.float64(),
        },
    ),
    "fct_pbp_game_teams_flat": TableSpec(
        "fct_pbp_game_teams_flat",
        ("gameid", "teamid"),
        {
            "gameid": pa.int64(),
            "teamid": pa.int64(),
            "opponentid": pa.int64(),
            "startdate": pa.string(),
            "ishometeam": pa.bool_(),
            "team_possessions": pa.float64(),
            "team_possessions_formula": pa.float64(),
            "opp_possessions": pa.float64(),
            "opp_possessions_formula": pa.float64(),
            "team_points_total": pa.float64(),
            "opp_points_total": pa.float64(),
            "team_2fg_made": pa.float64(),
            "team_2fg_att": pa.float64(),
            "team_3fg_made": pa.float64(),
            "team_3fg_att": pa.float64(),
            "team_ft_made": pa.float64(),
            "team_ft_att": pa.float64(),
            "team_fg_made": pa.float64(),
            "team_fg_att": pa.float64(),
            "team_tov_total": pa.float64(),
            "team_reb_off": pa.float64(),
            "team_reb_def": pa.float64(),
            "team_assists": pa.float64(),
            "team_steals": pa.float64(),
            "team_blocks": pa.float64(),
            "team_efg_pct": pa.float64(),
            "team_true_shooting": pa.float64(),
            "team_ft_rate": pa.float64(),
            "team_tov_ratio": pa.float64(),
            "team_oreb_pct": pa.float64(),
            "opp_2fg_made": pa.float64(),
            "opp_2fg_att": pa.float64(),
            "opp_3fg_made": pa.float64(),
            "opp_3fg_att": pa.float64(),
            "opp_ft_made": pa.float64(),
            "opp_ft_att": pa.float64(),
            "opp_fg_made": pa.float64(),
            "opp_fg_att": pa.float64(),
            "opp_tov_total": pa.float64(),
            "opp_reb_off": pa.float64(),
            "opp_reb_def": pa.float64(),
            "opp_assists": pa.float64(),
            "opp_steals": pa.float64(),
            "opp_blocks": pa.float64(),
            "opp_efg_pct": pa.float64(),
            "opp_true_shooting": pa.float64(),
            "opp_ft_rate": pa.float64(),
            "opp_tov_ratio": pa.float64(),
            "opp_oreb_pct": pa.float64(),
            "pace": pa.float64(),
            "garbage_time_minutes": pa.float64(),
            "game_minutes": pa.float64(),
            "max_period": pa.int64(),
        },
    ),
    "fct_pbp_game_teams_flat_garbage_removed": TableSpec(
        "fct_pbp_game_teams_flat_garbage_removed",
        ("gameid", "teamid"),
        {
            "gameid": pa.int64(),
            "teamid": pa.int64(),
            "opponentid": pa.int64(),
            "startdate": pa.string(),
            "ishometeam": pa.bool_(),
            "team_possessions": pa.float64(),
            "team_possessions_formula": pa.float64(),
            "opp_possessions": pa.float64(),
            "opp_possessions_formula": pa.float64(),
            "team_points_total": pa.float64(),
            "opp_points_total": pa.float64(),
            "team_2fg_made": pa.float64(),
            "team_2fg_att": pa.float64(),
            "team_3fg_made": pa.float64(),
            "team_3fg_att": pa.float64(),
            "team_ft_made": pa.float64(),
            "team_ft_att": pa.float64(),
            "team_fg_made": pa.float64(),
            "team_fg_att": pa.float64(),
            "team_tov_total": pa.float64(),
            "team_reb_off": pa.float64(),
            "team_reb_def": pa.float64(),
            "team_assists": pa.float64(),
            "team_steals": pa.float64(),
            "team_blocks": pa.float64(),
            "team_efg_pct": pa.float64(),
            "team_true_shooting": pa.float64(),
            "team_ft_rate": pa.float64(),
            "team_tov_ratio": pa.float64(),
            "team_oreb_pct": pa.float64(),
            "opp_2fg_made": pa.float64(),
            "opp_2fg_att": pa.float64(),
            "opp_3fg_made": pa.float64(),
            "opp_3fg_att": pa.float64(),
            "opp_ft_made": pa.float64(),
            "opp_ft_att": pa.float64(),
            "opp_fg_made": pa.float64(),
            "opp_fg_att": pa.float64(),
            "opp_tov_total": pa.float64(),
            "opp_reb_off": pa.float64(),
            "opp_reb_def": pa.float64(),
            "opp_assists": pa.float64(),
            "opp_steals": pa.float64(),
            "opp_blocks": pa.float64(),
            "opp_efg_pct": pa.float64(),
            "opp_true_shooting": pa.float64(),
            "opp_ft_rate": pa.float64(),
            "opp_tov_ratio": pa.float64(),
            "opp_oreb_pct": pa.float64(),
            "pace": pa.float64(),
            "garbage_time_minutes": pa.float64(),
            "game_minutes": pa.float64(),
            "max_period": pa.int64(),
        },
    ),
    "fct_pbp_team_daily_rollup": TableSpec(
        "fct_pbp_team_daily_rollup",
        ("teamid",),
        {
            "teamid": pa.int64(),
            "games_played": pa.int64(),
            "team_possessions": pa.float64(),
            "team_possessions_formula": pa.float64(),
            "opp_possessions": pa.float64(),
            "opp_possessions_formula": pa.float64(),
            "team_points_total": pa.float64(),
            "opp_points_total": pa.float64(),
            "team_2fg_made": pa.float64(),
            "team_2fg_att": pa.float64(),
            "team_3fg_made": pa.float64(),
            "team_3fg_att": pa.float64(),
            "team_ft_made": pa.float64(),
            "team_ft_att": pa.float64(),
            "team_fg_made": pa.float64(),
            "team_fg_att": pa.float64(),
            "team_tov_total": pa.float64(),
            "team_reb_off": pa.float64(),
            "team_reb_def": pa.float64(),
            "team_assists": pa.float64(),
            "team_steals": pa.float64(),
            "team_blocks": pa.float64(),
            "opp_2fg_made": pa.float64(),
            "opp_2fg_att": pa.float64(),
            "opp_3fg_made": pa.float64(),
            "opp_3fg_att": pa.float64(),
            "opp_ft_made": pa.float64(),
            "opp_ft_att": pa.float64(),
            "opp_fg_made": pa.float64(),
            "opp_fg_att": pa.float64(),
            "opp_tov_total": pa.float64(),
            "opp_reb_off": pa.float64(),
            "opp_reb_def": pa.float64(),
            "opp_assists": pa.float64(),
            "opp_steals": pa.float64(),
            "opp_blocks": pa.float64(),
            "team_efg_pct": pa.float64(),
            "team_true_shooting": pa.float64(),
            "team_ft_rate": pa.float64(),
            "team_tov_ratio": pa.float64(),
            "team_oreb_pct": pa.float64(),
            "opp_efg_pct": pa.float64(),
            "opp_true_shooting": pa.float64(),
            "opp_ft_rate": pa.float64(),
            "opp_tov_ratio": pa.float64(),
            "opp_oreb_pct": pa.float64(),
            "pace": pa.float64(),
            "pace_formula": pa.float64(),
            "team_points_per_game": pa.float64(),
            "opp_points_per_game": pa.float64(),
            "team_points_per_poss": pa.float64(),
            "team_points_per_poss_formula": pa.float64(),
            "opp_points_per_poss": pa.float64(),
            "opp_points_per_poss_formula": pa.float64(),
            "team_fga_per_game": pa.float64(),
            "team_fta_per_game": pa.float64(),
            "team_tov_per_game": pa.float64(),
            "team_reb_off_per_game": pa.float64(),
            "team_reb_def_per_game": pa.float64(),
            "team_assists_per_game": pa.float64(),
            "team_steals_per_game": pa.float64(),
            "team_blocks_per_game": pa.float64(),
            "team_fga_per_poss": pa.float64(),
            "team_fta_per_poss": pa.float64(),
            "team_tov_per_poss": pa.float64(),
            "team_reb_off_per_poss": pa.float64(),
            "team_reb_def_per_poss": pa.float64(),
            "team_assists_per_poss": pa.float64(),
            "team_steals_per_poss": pa.float64(),
            "team_blocks_per_poss": pa.float64(),
            "team_fga_per_poss_formula": pa.float64(),
            "team_fta_per_poss_formula": pa.float64(),
            "team_tov_per_poss_formula": pa.float64(),
            "team_reb_off_per_poss_formula": pa.float64(),
            "team_reb_def_per_poss_formula": pa.float64(),
            "team_assists_per_poss_formula": pa.float64(),
            "team_steals_per_poss_formula": pa.float64(),
            "team_blocks_per_poss_formula": pa.float64(),
            "opp_fga_per_game": pa.float64(),
            "opp_fta_per_game": pa.float64(),
            "opp_tov_per_game": pa.float64(),
            "opp_reb_off_per_game": pa.float64(),
            "opp_reb_def_per_game": pa.float64(),
            "opp_assists_per_game": pa.float64(),
            "opp_steals_per_game": pa.float64(),
            "opp_blocks_per_game": pa.float64(),
            "opp_fga_per_poss": pa.float64(),
            "opp_fta_per_poss": pa.float64(),
            "opp_tov_per_poss": pa.float64(),
            "opp_reb_off_per_poss": pa.float64(),
            "opp_reb_def_per_poss": pa.float64(),
            "opp_assists_per_poss": pa.float64(),
            "opp_steals_per_poss": pa.float64(),
            "opp_blocks_per_poss": pa.float64(),
            "opp_fga_per_poss_formula": pa.float64(),
            "opp_fta_per_poss_formula": pa.float64(),
            "opp_tov_per_poss_formula": pa.float64(),
            "opp_reb_off_per_poss_formula": pa.float64(),
            "opp_reb_def_per_poss_formula": pa.float64(),
            "opp_assists_per_poss_formula": pa.float64(),
            "opp_steals_per_poss_formula": pa.float64(),
            "opp_blocks_per_poss_formula": pa.float64(),
            "game_minutes_total": pa.float64(),
        },
    ),
    "fct_pbp_team_daily_rollup_garbage_removed": TableSpec(
        "fct_pbp_team_daily_rollup_garbage_removed",
        ("teamid",),
        {
            "teamid": pa.int64(),
            "games_played": pa.int64(),
            "team_possessions": pa.float64(),
            "team_possessions_formula": pa.float64(),
            "opp_possessions": pa.float64(),
            "opp_possessions_formula": pa.float64(),
            "team_points_total": pa.float64(),
            "opp_points_total": pa.float64(),
            "team_2fg_made": pa.float64(),
            "team_2fg_att": pa.float64(),
            "team_3fg_made": pa.float64(),
            "team_3fg_att": pa.float64(),
            "team_ft_made": pa.float64(),
            "team_ft_att": pa.float64(),
            "team_fg_made": pa.float64(),
            "team_fg_att": pa.float64(),
            "team_tov_total": pa.float64(),
            "team_reb_off": pa.float64(),
            "team_reb_def": pa.float64(),
            "team_assists": pa.float64(),
            "team_steals": pa.float64(),
            "team_blocks": pa.float64(),
            "opp_2fg_made": pa.float64(),
            "opp_2fg_att": pa.float64(),
            "opp_3fg_made": pa.float64(),
            "opp_3fg_att": pa.float64(),
            "opp_ft_made": pa.float64(),
            "opp_ft_att": pa.float64(),
            "opp_fg_made": pa.float64(),
            "opp_fg_att": pa.float64(),
            "opp_tov_total": pa.float64(),
            "opp_reb_off": pa.float64(),
            "opp_reb_def": pa.float64(),
            "opp_assists": pa.float64(),
            "opp_steals": pa.float64(),
            "opp_blocks": pa.float64(),
            "team_efg_pct": pa.float64(),
            "team_true_shooting": pa.float64(),
            "team_ft_rate": pa.float64(),
            "team_tov_ratio": pa.float64(),
            "team_oreb_pct": pa.float64(),
            "opp_efg_pct": pa.float64(),
            "opp_true_shooting": pa.float64(),
            "opp_ft_rate": pa.float64(),
            "opp_tov_ratio": pa.float64(),
            "opp_oreb_pct": pa.float64(),
            "pace": pa.float64(),
            "pace_formula": pa.float64(),
            "team_points_per_game": pa.float64(),
            "opp_points_per_game": pa.float64(),
            "team_points_per_poss": pa.float64(),
            "team_points_per_poss_formula": pa.float64(),
            "opp_points_per_poss": pa.float64(),
            "opp_points_per_poss_formula": pa.float64(),
            "team_fga_per_game": pa.float64(),
            "team_fta_per_game": pa.float64(),
            "team_tov_per_game": pa.float64(),
            "team_reb_off_per_game": pa.float64(),
            "team_reb_def_per_game": pa.float64(),
            "team_assists_per_game": pa.float64(),
            "team_steals_per_game": pa.float64(),
            "team_blocks_per_game": pa.float64(),
            "team_fga_per_poss": pa.float64(),
            "team_fta_per_poss": pa.float64(),
            "team_tov_per_poss": pa.float64(),
            "team_reb_off_per_poss": pa.float64(),
            "team_reb_def_per_poss": pa.float64(),
            "team_assists_per_poss": pa.float64(),
            "team_steals_per_poss": pa.float64(),
            "team_blocks_per_poss": pa.float64(),
            "team_fga_per_poss_formula": pa.float64(),
            "team_fta_per_poss_formula": pa.float64(),
            "team_tov_per_poss_formula": pa.float64(),
            "team_reb_off_per_poss_formula": pa.float64(),
            "team_reb_def_per_poss_formula": pa.float64(),
            "team_assists_per_poss_formula": pa.float64(),
            "team_steals_per_poss_formula": pa.float64(),
            "team_blocks_per_poss_formula": pa.float64(),
            "opp_fga_per_game": pa.float64(),
            "opp_fta_per_game": pa.float64(),
            "opp_tov_per_game": pa.float64(),
            "opp_reb_off_per_game": pa.float64(),
            "opp_reb_def_per_game": pa.float64(),
            "opp_assists_per_game": pa.float64(),
            "opp_steals_per_game": pa.float64(),
            "opp_blocks_per_game": pa.float64(),
            "opp_fga_per_poss": pa.float64(),
            "opp_fta_per_poss": pa.float64(),
            "opp_tov_per_poss": pa.float64(),
            "opp_reb_off_per_poss": pa.float64(),
            "opp_reb_def_per_poss": pa.float64(),
            "opp_assists_per_poss": pa.float64(),
            "opp_steals_per_poss": pa.float64(),
            "opp_blocks_per_poss": pa.float64(),
            "opp_fga_per_poss_formula": pa.float64(),
            "opp_fta_per_poss_formula": pa.float64(),
            "opp_tov_per_poss_formula": pa.float64(),
            "opp_reb_off_per_poss_formula": pa.float64(),
            "opp_reb_def_per_poss_formula": pa.float64(),
            "opp_assists_per_poss_formula": pa.float64(),
            "opp_steals_per_poss_formula": pa.float64(),
            "opp_blocks_per_poss_formula": pa.float64(),
            "game_minutes_total": pa.float64(),
        },
    ),
    "fct_pbp_team_daily_rollup_adj": TableSpec(
        "fct_pbp_team_daily_rollup_adj",
        ("teamid",),
        {
            "teamid": pa.int64(),
            "adj_off_eff": pa.float64(),
            "adj_def_eff": pa.float64(),
            "adj_net_eff": pa.float64(),
            "adj_off_eff_formula": pa.float64(),
            "adj_def_eff_formula": pa.float64(),
            "adj_net_eff_formula": pa.float64(),
            "weighted_off_eff": pa.float64(),
            "weighted_def_eff": pa.float64(),
            "weighted_off_eff_formula": pa.float64(),
            "weighted_def_eff_formula": pa.float64(),
            "hca_points_per_100": pa.float64(),
        },
    ),
    "fct_pbp_team_daily_rollup_adj_garbage_removed": TableSpec(
        "fct_pbp_team_daily_rollup_adj_garbage_removed",
        ("teamid",),
        {
            "teamid": pa.int64(),
            "adj_off_eff": pa.float64(),
            "adj_def_eff": pa.float64(),
            "adj_net_eff": pa.float64(),
            "adj_off_eff_formula": pa.float64(),
            "adj_def_eff_formula": pa.float64(),
            "adj_net_eff_formula": pa.float64(),
            "weighted_off_eff": pa.float64(),
            "weighted_def_eff": pa.float64(),
            "weighted_off_eff_formula": pa.float64(),
            "weighted_def_eff_formula": pa.float64(),
            "hca_points_per_100": pa.float64(),
        },
    ),
    "fct_plays": TableSpec(
        "fct_plays",
        ("id",),
        {
            "id": pa.int64(),
            "gameId": pa.int64(),
            "onfloor_player1": pa.int64(),
            "onfloor_player2": pa.int64(),
            "onfloor_player3": pa.int64(),
            "onfloor_player4": pa.int64(),
            "onfloor_player5": pa.int64(),
            "onfloor_player6": pa.int64(),
            "onfloor_player7": pa.int64(),
            "onfloor_player8": pa.int64(),
            "onfloor_player9": pa.int64(),
            "onfloor_player10": pa.int64(),
            "participant_id": pa.int64(),
            "shot_shooter_id": pa.int64(),
            "shot_shooter_name": pa.string(),
            "shot_made": pa.bool_(),
            "shot_range": pa.string(),
            "shot_assisted": pa.bool_(),
            "shot_assisted_by_id": pa.int64(),
            "shot_assisted_by_name": pa.string(),
            "shot_loc_x": pa.float64(),
            "shot_loc_y": pa.float64(),
        },
    ),
    "fct_substitutions": TableSpec("fct_substitutions", ("id",), {"id": pa.int64(), "gameId": pa.int64()}),
    "fct_lineups": TableSpec(
        "fct_lineups",
        ("idHash", "teamId", "totalSeconds"),
        {
            "athletes": pa.string(),
            "conference": pa.string(),
            "defenserating": pa.float64(),
            "idhash": pa.string(),
            "netrating": pa.float64(),
            "offenserating": pa.float64(),
            "opponentstats": pa.string(),
            "pace": pa.float64(),
            "team": pa.string(),
            "teamid": pa.int64(),
            "teamstats": pa.string(),
            "totalseconds": pa.float64(),
        },
    ),
    "fct_rankings": TableSpec(
        "fct_rankings",
        ("season", "pollDate", "pollType", "teamId"),
        {
            "season": pa.int32(),
            "pollDate": pa.string(),
            "pollType": pa.string(),
            "teamId": pa.int64(),
            "week": pa.int64(),
            "ranking": pa.int64(),
            "points": pa.int64(),
            "firstPlaceVotes": pa.int64(),
        },
    ),
    "fct_ratings_adjusted": TableSpec(
        "fct_ratings_adjusted",
        ("teamid", "season"),
        {
            "season": pa.int32(),
            "teamid": pa.int64(),
            "team": pa.string(),
            "conference": pa.string(),
            "offenserating": pa.float64(),
            "defenserating": pa.float64(),
            "netrating": pa.float64(),
            "ranking_offense": pa.int64(),
            "ranking_defense": pa.int64(),
            "ranking_net": pa.int64(),
        },
    ),
    "fct_ratings_srs": TableSpec("fct_ratings_srs", ("teamId", "season"), {"teamId": pa.int64(), "season": pa.int32()}),
    "fct_team_season_stats": TableSpec("fct_team_season_stats", ("teamId", "season"), {"teamId": pa.int64(), "season": pa.int32()}),
    "fct_team_season_shooting": TableSpec("fct_team_season_shooting", ("teamId", "season"), {"teamId": pa.int64(), "season": pa.int32()}),
    "fct_player_season_stats": TableSpec("fct_player_season_stats", ("playerId", "season"), {"playerId": pa.int64(), "season": pa.int32()}),
    "fct_player_season_shooting": TableSpec("fct_player_season_shooting", ("playerId", "season"), {"playerId": pa.int64(), "season": pa.int32()}),
    "fct_recruiting_players": TableSpec("fct_recruiting_players", ("playerId", "season"), {"playerId": pa.int64(), "season": pa.int32()}),
    "fct_draft_picks": TableSpec("fct_draft_picks", ("id",), {"id": pa.int64()}),
}


def _cast_value(value: Any, dtype: pa.DataType) -> Any:
    if value is None:
        return None
    if pa.types.is_int64(dtype) or pa.types.is_int32(dtype):
        try:
            return int(value)
        except Exception:
            return None
    if pa.types.is_float64(dtype):
        try:
            return float(value)
        except Exception:
            return None
    if pa.types.is_boolean(dtype):
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            return value.lower() in ("true", "1", "yes")
        return bool(value)
    if pa.types.is_timestamp(dtype):
        try:
            return parser.parse(str(value))
        except Exception:
            return None
    return str(value)


def _infer_type(value: Any) -> pa.DataType:
    if isinstance(value, bool):
        return pa.bool_()
    if isinstance(value, int):
        return pa.int64()
    if isinstance(value, float):
        return pa.float64()
    return pa.string()


def normalize_records(table_name: str, records: List[Dict[str, Any]]) -> pa.Table:
    spec = TABLE_SPECS.get(table_name)
    type_hints: Dict[str, pa.DataType] = {}
    if spec:
        type_hints.update(spec.type_hints)
    type_hints.update(COMMON_TYPE_HINTS)

    all_fields = set()
    for rec in records:
        all_fields.update(rec.keys())

    schema_fields: List[pa.Field] = []
    for field in sorted(all_fields):
        dtype = type_hints.get(field)
        if dtype is None:
            sample = next((r.get(field) for r in records if r.get(field) is not None), None)
            dtype = _infer_type(sample)
        schema_fields.append(pa.field(field, dtype))

    schema = pa.schema(schema_fields)
    normalized: List[Dict[str, Any]] = []
    for rec in records:
        row: Dict[str, Any] = {}
        for field in schema.names:
            dtype = schema.field(field).type
            row[field] = _cast_value(rec.get(field), dtype)
        normalized.append(row)
    return pa.Table.from_pylist(normalized, schema=schema)


def dedupe_records(records: List[Dict[str, Any]], key_fields: Tuple[str, ...]) -> List[Dict[str, Any]]:
    if not key_fields:
        return records
    seen = set()
    deduped: List[Dict[str, Any]] = []
    for rec in records:
        key = tuple(rec.get(k) for k in key_fields)
        if key in seen:
            continue
        seen.add(key)
        deduped.append(rec)
    return deduped
